function normalizeAlias(value = "") {
  return String(value || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]/g, "")
    .trim();
}

function createNumericLab({
  key,
  group,
  displayName,
  aliases = [],
  unit = "",
  plausibilityMin = null,
  plausibilityMax = null,
  expectedRangeText = "",
  panelMemberships = [],
}) {
  return {
    key,
    group,
    displayName,
    aliases,
    resultType: "numeric",
    unit,
    plausibilityMin,
    plausibilityMax,
    expectedRangeText,
    panelMemberships,
  };
}

function createCategoricalLab({
  key,
  group,
  displayName,
  aliases = [],
  allowedValues = [],
  panelMemberships = [],
}) {
  return {
    key,
    group,
    displayName,
    aliases,
    resultType: "categorical",
    allowedValues,
    panelMemberships,
  };
}

export const CATEGORICAL_VALUE_SETS = {
  reactive: ["Reactive", "Non-Reactive"],
  detected: ["Detected", "Not Detected"],
  positive: ["Positive", "Negative"],
  extended: [
    "Reactive",
    "Non-Reactive",
    "Detected",
    "Not Detected",
    "Positive",
    "Negative",
    "Indeterminate",
    "Equivocal",
  ],
  urineDipstick: ["Negative", "Trace", "1+", "2+", "3+", "4+"],
};

export const LAB_CATALOG = [
  // =========================
  // CBC
  // =========================
  createNumericLab({
    key: "wbc",
    group: "CBC",
    displayName: "White Blood Cell Count",
    aliases: [
      "wbc",
      "white blood cell",
      "white blood cell count",
      "leukocytes",
      "leukocyte count",
      "wbcc",
    ],
    unit: "x10^3/uL",
    plausibilityMin: 0.1,
    plausibilityMax: 200,
    expectedRangeText: "~4.0-11.0",
    panelMemberships: ["CBC", "CBC with Differential"],
  }),
  createNumericLab({
    key: "rbc",
    group: "CBC",
    displayName: "Red Blood Cell Count",
    aliases: [
      "rbc",
      "red blood cell",
      "red blood cell count",
      "erythrocytes",
      "erythrocyte count",
    ],
    unit: "x10^6/uL",
    plausibilityMin: 0.5,
    plausibilityMax: 10,
    expectedRangeText: "~3.5-6.0",
    panelMemberships: ["CBC", "CBC with Differential"],
  }),
  createNumericLab({
    key: "hemoglobin",
    group: "CBC",
    displayName: "Hemoglobin",
    aliases: ["hemoglobin", "hgb", "hb"],
    unit: "g/dL",
    plausibilityMin: 1,
    plausibilityMax: 25,
    expectedRangeText: "~10-18",
    panelMemberships: ["CBC", "CBC with Differential"],
  }),
  createNumericLab({
    key: "hematocrit",
    group: "CBC",
    displayName: "Hematocrit",
    aliases: ["hematocrit", "hct"],
    unit: "%",
    plausibilityMin: 5,
    plausibilityMax: 80,
    expectedRangeText: "~30-55",
    panelMemberships: ["CBC", "CBC with Differential"],
  }),
  createNumericLab({
    key: "mcv",
    group: "CBC",
    displayName: "MCV",
    aliases: ["mcv", "mean corpuscular volume"],
    unit: "fL",
    plausibilityMin: 40,
    plausibilityMax: 150,
    expectedRangeText: "~80-100",
    panelMemberships: ["CBC", "CBC with Differential"],
  }),
  createNumericLab({
    key: "mch",
    group: "CBC",
    displayName: "MCH",
    aliases: ["mch", "mean corpuscular hemoglobin"],
    unit: "pg",
    plausibilityMin: 10,
    plausibilityMax: 60,
    expectedRangeText: "~25-35",
    panelMemberships: ["CBC", "CBC with Differential"],
  }),
  createNumericLab({
    key: "mchc",
    group: "CBC",
    displayName: "MCHC",
    aliases: ["mchc", "mean corpuscular hemoglobin concentration"],
    unit: "g/dL",
    plausibilityMin: 20,
    plausibilityMax: 45,
    expectedRangeText: "~31-37",
    panelMemberships: ["CBC", "CBC with Differential"],
  }),
  createNumericLab({
    key: "rdw",
    group: "CBC",
    displayName: "RDW",
    aliases: ["rdw", "rdwcv", "rdw cv", "rdw-cv", "red cell distribution width"],
    unit: "%",
    plausibilityMin: 5,
    plausibilityMax: 40,
    expectedRangeText: "~11-16",
    panelMemberships: ["CBC", "CBC with Differential"],
  }),
  createNumericLab({
    key: "platelets",
    group: "CBC",
    displayName: "Platelet Count",
    aliases: ["platelets", "platelet", "platelet count", "plt"],
    unit: "x10^3/uL",
    plausibilityMin: 1,
    plausibilityMax: 2000,
    expectedRangeText: "~150-450",
    panelMemberships: ["CBC", "CBC with Differential"],
  }),
  createNumericLab({
    key: "mpv",
    group: "CBC",
    displayName: "MPV",
    aliases: ["mpv", "mean platelet volume"],
    unit: "fL",
    plausibilityMin: 3,
    plausibilityMax: 20,
    expectedRangeText: "~7-12",
    panelMemberships: ["CBC", "CBC with Differential"],
  }),

  // =========================
  // Differential
  // =========================
  createNumericLab({
    key: "neutrophils_percent",
    group: "Differential",
    displayName: "Neutrophils %",
    aliases: [
      "neutrophils",
      "neutrophils percent",
      "neutrophils %",
      "neut %",
      "segs",
      "segmented neutrophils",
    ],
    unit: "%",
    plausibilityMin: 0,
    plausibilityMax: 100,
    expectedRangeText: "~40-75",
    panelMemberships: ["CBC with Differential"],
  }),
  createNumericLab({
    key: "lymphocytes_percent",
    group: "Differential",
    displayName: "Lymphocytes %",
    aliases: [
      "lymphocytes",
      "lymphocytes percent",
      "lymphocytes %",
      "lymph %",
      "lymphs",
    ],
    unit: "%",
    plausibilityMin: 0,
    plausibilityMax: 100,
    expectedRangeText: "~15-45",
    panelMemberships: ["CBC with Differential"],
  }),
  createNumericLab({
    key: "monocytes_percent",
    group: "Differential",
    displayName: "Monocytes %",
    aliases: ["monocytes", "monocytes percent", "monocytes %", "mono %", "monos"],
    unit: "%",
    plausibilityMin: 0,
    plausibilityMax: 100,
    expectedRangeText: "~2-12",
    panelMemberships: ["CBC with Differential"],
  }),
  createNumericLab({
    key: "eosinophils_percent",
    group: "Differential",
    displayName: "Eosinophils %",
    aliases: ["eosinophils", "eosinophils percent", "eosinophils %", "eos %", "eos"],
    unit: "%",
    plausibilityMin: 0,
    plausibilityMax: 100,
    expectedRangeText: "~0-8",
    panelMemberships: ["CBC with Differential"],
  }),
  createNumericLab({
    key: "basophils_percent",
    group: "Differential",
    displayName: "Basophils %",
    aliases: ["basophils", "basophils percent", "basophils %", "baso %", "basos"],
    unit: "%",
    plausibilityMin: 0,
    plausibilityMax: 100,
    expectedRangeText: "~0-3",
    panelMemberships: ["CBC with Differential"],
  }),
  createNumericLab({
    key: "immature_granulocytes_percent",
    group: "Differential",
    displayName: "Immature Granulocytes %",
    aliases: [
      "immature granulocytes",
      "immature granulocytes percent",
      "immature granulocytes %",
      "immature grans",
      "ig %",
      "ig",
    ],
    unit: "%",
    plausibilityMin: 0,
    plausibilityMax: 100,
    expectedRangeText: "~0-2",
    panelMemberships: ["CBC with Differential"],
  }),
  createNumericLab({
    key: "anc",
    group: "Differential",
    displayName: "Absolute Neutrophil Count",
    aliases: [
      "anc",
      "absolute neutrophil count",
      "neutrophils absolute",
      "abs neut",
      "absolute neutrophils",
    ],
    unit: "x10^3/uL",
    plausibilityMin: 0,
    plausibilityMax: 100,
    expectedRangeText: "~1.5-8.0",
    panelMemberships: ["CBC with Differential"],
  }),
  createNumericLab({
    key: "absolute_lymphocytes",
    group: "Differential",
    displayName: "Absolute Lymphocytes",
    aliases: ["lymphocytes absolute", "absolute lymphocytes", "abs lymph", "alc"],
    unit: "x10^3/uL",
    plausibilityMin: 0,
    plausibilityMax: 50,
    expectedRangeText: "~1.0-4.5",
    panelMemberships: ["CBC with Differential"],
  }),
  createNumericLab({
    key: "absolute_monocytes",
    group: "Differential",
    displayName: "Absolute Monocytes",
    aliases: ["monocytes absolute", "absolute monocytes", "abs mono"],
    unit: "x10^3/uL",
    plausibilityMin: 0,
    plausibilityMax: 20,
    expectedRangeText: "~0.2-1.0",
    panelMemberships: ["CBC with Differential"],
  }),
  createNumericLab({
    key: "absolute_eosinophils",
    group: "Differential",
    displayName: "Absolute Eosinophils",
    aliases: ["eosinophils absolute", "absolute eosinophils", "abs eos"],
    unit: "x10^3/uL",
    plausibilityMin: 0,
    plausibilityMax: 20,
    expectedRangeText: "~0.0-0.5",
    panelMemberships: ["CBC with Differential"],
  }),
  createNumericLab({
    key: "absolute_basophils",
    group: "Differential",
    displayName: "Absolute Basophils",
    aliases: ["basophils absolute", "absolute basophils", "abs baso"],
    unit: "x10^3/uL",
    plausibilityMin: 0,
    plausibilityMax: 20,
    expectedRangeText: "~0.0-0.2",
    panelMemberships: ["CBC with Differential"],
  }),

  // =========================
  // BMP / CMP / Chemistry
  // =========================
  createNumericLab({
    key: "sodium",
    group: "Chemistry",
    displayName: "Sodium",
    aliases: ["sodium", "sodium level", "na+"],
    unit: "mmol/L",
    plausibilityMin: 90,
    plausibilityMax: 200,
    expectedRangeText: "~135-145",
    panelMemberships: ["BMP", "CMP", "Renal Function Panel"],
  }),
  createNumericLab({
    key: "potassium",
    group: "Chemistry",
    displayName: "Potassium",
    aliases: ["potassium", "potassium level", "k+"],
    unit: "mmol/L",
    plausibilityMin: 1,
    plausibilityMax: 10,
    expectedRangeText: "~3.5-5.2",
    panelMemberships: ["BMP", "CMP", "Renal Function Panel"],
  }),
  createNumericLab({
    key: "chloride",
    group: "Chemistry",
    displayName: "Chloride",
    aliases: ["chloride", "chloride level", "cl-"],
    unit: "mmol/L",
    plausibilityMin: 50,
    plausibilityMax: 150,
    expectedRangeText: "~96-110",
    panelMemberships: ["BMP", "CMP", "Renal Function Panel"],
  }),
  createNumericLab({
    key: "co2",
    group: "Chemistry",
    displayName: "CO2 / Bicarbonate",
    aliases: ["co2", "carbon dioxide", "bicarbonate", "hco3", "total co2"],
    unit: "mmol/L",
    plausibilityMin: 5,
    plausibilityMax: 60,
    expectedRangeText: "~20-32",
    panelMemberships: ["BMP", "CMP", "Renal Function Panel"],
  }),
  createNumericLab({
    key: "anion_gap",
    group: "Chemistry",
    displayName: "Anion Gap",
    aliases: ["anion gap", "agap", "an gap"],
    unit: "mmol/L",
    plausibilityMin: 0,
    plausibilityMax: 50,
    expectedRangeText: "~5-18",
    panelMemberships: ["BMP", "CMP"],
  }),
  createNumericLab({
    key: "glucose",
    group: "Chemistry",
    displayName: "Glucose",
    aliases: ["glucose", "glucose level", "blood glucose", "serum glucose"],
    unit: "mg/dL",
    plausibilityMin: 10,
    plausibilityMax: 1000,
    expectedRangeText: "~70-140",
    panelMemberships: ["BMP", "CMP", "Renal Function Panel"],
  }),
  createNumericLab({
    key: "bun",
    group: "Chemistry",
    displayName: "BUN",
    aliases: ["bun", "blood urea nitrogen", "urea nitrogen"],
    unit: "mg/dL",
    plausibilityMin: 1,
    plausibilityMax: 300,
    expectedRangeText: "~6-25",
    panelMemberships: ["BMP", "CMP", "Renal Function Panel"],
  }),
  createNumericLab({
    key: "creatinine",
    group: "Chemistry",
    displayName: "Creatinine",
    aliases: ["creatinine", "cr", "creat", "serum creatinine"],
    unit: "mg/dL",
    plausibilityMin: 0.1,
    plausibilityMax: 20,
    expectedRangeText: "~0.5-1.5",
    panelMemberships: ["BMP", "CMP", "Renal Function Panel"],
  }),
  createNumericLab({
    key: "egfr",
    group: "Renal",
    displayName: "eGFR",
    aliases: [
      "egfr",
      "e gfr",
      "estimated gfr",
      "glomerular filtration rate",
      "egfr non-aa",
      "egfr aa",
    ],
    unit: "mL/min/1.73m2",
    plausibilityMin: 1,
    plausibilityMax: 200,
    expectedRangeText: "~60+",
    panelMemberships: ["BMP", "CMP", "Renal Function Panel"],
  }),
  createNumericLab({
    key: "calcium",
    group: "Chemistry",
    displayName: "Calcium",
    aliases: ["calcium", "ca", "total calcium"],
    unit: "mg/dL",
    plausibilityMin: 3,
    plausibilityMax: 20,
    expectedRangeText: "~8.5-10.5",
    panelMemberships: ["BMP", "CMP", "Renal Function Panel"],
  }),
  createNumericLab({
    key: "phosphorus",
    group: "Renal",
    displayName: "Phosphorus",
    aliases: ["phosphorus", "phosphorous", "phosphate", "phos"],
    unit: "mg/dL",
    plausibilityMin: 0.5,
    plausibilityMax: 15,
    expectedRangeText: "~2.5-4.5",
    panelMemberships: ["Renal Function Panel"],
  }),
  createNumericLab({
    key: "magnesium",
    group: "Chemistry",
    displayName: "Magnesium",
    aliases: ["magnesium"],
    unit: "mg/dL",
    plausibilityMin: 0.5,
    plausibilityMax: 10,
    expectedRangeText: "~1.5-2.5",
    panelMemberships: [],
  }),

  // =========================
  // Liver
  // =========================
  createNumericLab({
    key: "total_protein",
    group: "Liver",
    displayName: "Total Protein",
    aliases: ["total protein", "protein total"],
    unit: "g/dL",
    plausibilityMin: 2,
    plausibilityMax: 12,
    expectedRangeText: "~6.0-8.5",
    panelMemberships: ["CMP"],
  }),
  createNumericLab({
    key: "albumin",
    group: "Liver",
    displayName: "Albumin",
    aliases: ["albumin", "alb"],
    unit: "g/dL",
    plausibilityMin: 0.5,
    plausibilityMax: 8,
    expectedRangeText: "~3.5-5.5",
    panelMemberships: ["CMP", "Renal Function Panel"],
  }),
  createNumericLab({
    key: "globulin",
    group: "Liver",
    displayName: "Globulin",
    aliases: ["globulin", "glob"],
    unit: "g/dL",
    plausibilityMin: 0.5,
    plausibilityMax: 8,
    expectedRangeText: "~2.0-4.0",
    panelMemberships: ["CMP"],
  }),
  createNumericLab({
    key: "ag_ratio",
    group: "Liver",
    displayName: "A/G Ratio",
    aliases: ["a/g ratio", "ag ratio", "albumin/globulin ratio"],
    unit: "",
    plausibilityMin: 0.1,
    plausibilityMax: 10,
    expectedRangeText: "~1.0-2.5",
    panelMemberships: ["CMP"],
  }),
  createNumericLab({
    key: "total_bilirubin",
    group: "Liver",
    displayName: "Total Bilirubin",
    aliases: ["total bilirubin", "bilirubin total", "tbili", "bili total"],
    unit: "mg/dL",
    plausibilityMin: 0,
    plausibilityMax: 40,
    expectedRangeText: "~0.1-1.2",
    panelMemberships: ["CMP"],
  }),
  createNumericLab({
    key: "direct_bilirubin",
    group: "Liver",
    displayName: "Direct Bilirubin",
    aliases: ["direct bilirubin", "bilirubin direct", "dbili"],
    unit: "mg/dL",
    plausibilityMin: 0,
    plausibilityMax: 20,
    expectedRangeText: "~0.0-0.3",
    panelMemberships: [],
  }),
  createNumericLab({
    key: "ast",
    group: "Liver",
    displayName: "AST",
    aliases: ["ast", "sgot", "aspartate aminotransferase"],
    unit: "U/L",
    plausibilityMin: 0,
    plausibilityMax: 5000,
    expectedRangeText: "~10-40",
    panelMemberships: ["CMP"],
  }),
  createNumericLab({
    key: "alt",
    group: "Liver",
    displayName: "ALT",
    aliases: ["alt", "sgpt", "alanine aminotransferase"],
    unit: "U/L",
    plausibilityMin: 0,
    plausibilityMax: 5000,
    expectedRangeText: "~7-56",
    panelMemberships: ["CMP"],
  }),
  createNumericLab({
    key: "alkaline_phosphatase",
    group: "Liver",
    displayName: "Alkaline Phosphatase",
    aliases: ["alkaline phosphatase", "alk phos", "alkphos", "alp"],
    unit: "U/L",
    plausibilityMin: 1,
    plausibilityMax: 3000,
    expectedRangeText: "~40-130",
    panelMemberships: ["CMP"],
  }),
  createNumericLab({
    key: "ggt",
    group: "Liver",
    displayName: "GGT",
    aliases: ["ggt", "gamma gt", "gamma glutamyl transferase"],
    unit: "U/L",
    plausibilityMin: 0,
    plausibilityMax: 3000,
    expectedRangeText: "~0-60",
    panelMemberships: [],
  }),

  // =========================
  // Diabetes / Endocrine
  // =========================
  createNumericLab({
    key: "a1c",
    group: "Diabetes / Endocrine",
    displayName: "Hemoglobin A1c",
    aliases: ["a1c", "hba1c", "hemoglobin a1c", "glycated hemoglobin", "glycohemoglobin"],
    unit: "%",
    plausibilityMin: 3,
    plausibilityMax: 20,
    expectedRangeText: "~4.0-6.5",
    panelMemberships: [],
  }),
  createNumericLab({
    key: "estimated_average_glucose",
    group: "Diabetes / Endocrine",
    displayName: "Estimated Average Glucose",
    aliases: ["estimated average glucose", "eag", "avg glucose"],
    unit: "mg/dL",
    plausibilityMin: 20,
    plausibilityMax: 500,
    expectedRangeText: "~70-140",
    panelMemberships: [],
  }),
  createNumericLab({
    key: "insulin",
    group: "Diabetes / Endocrine",
    displayName: "Insulin",
    aliases: ["insulin", "fasting insulin"],
    unit: "uIU/mL",
    plausibilityMin: 0,
    plausibilityMax: 500,
    expectedRangeText: "~2-25",
    panelMemberships: [],
  }),

  // =========================
  // Thyroid
  // =========================
  createNumericLab({
    key: "tsh",
    group: "Thyroid",
    displayName: "TSH",
    aliases: ["tsh", "tsh 3rd generation", "thyroid stimulating hormone", "thyroid-stimulating hormone"],
    unit: "uIU/mL",
    plausibilityMin: 0,
    plausibilityMax: 200,
    expectedRangeText: "~0.4-4.5",
    panelMemberships: ["Thyroid Panel"],
  }),
  createNumericLab({
    key: "free_t4",
    group: "Thyroid",
    displayName: "Free T4",
    aliases: ["free t4", "t4 free", "ft4", "thyroxine free"],
    unit: "ng/dL",
    plausibilityMin: 0,
    plausibilityMax: 10,
    expectedRangeText: "~0.8-1.8",
    panelMemberships: ["Thyroid Panel"],
  }),
  createNumericLab({
    key: "total_t4",
    group: "Thyroid",
    displayName: "Total T4",
    aliases: ["total t4", "t4", "thyroxine", "procedure t4"],
    unit: "ug/dL",
    plausibilityMin: 0,
    plausibilityMax: 30,
    expectedRangeText: "~4.5-12.5",
    panelMemberships: ["Thyroid Panel"],
  }),
  createNumericLab({
    key: "free_t3",
    group: "Thyroid",
    displayName: "Free T3",
    aliases: ["free t3", "ft3", "triiodothyronine free"],
    unit: "pg/mL",
    plausibilityMin: 0,
    plausibilityMax: 20,
    expectedRangeText: "~2.0-4.5",
    panelMemberships: ["Thyroid Panel"],
  }),
  createNumericLab({
    key: "total_t3",
    group: "Thyroid",
    displayName: "Total T3",
    aliases: ["total t3", "t3", "triiodothyronine"],
    unit: "ng/dL",
    plausibilityMin: 0,
    plausibilityMax: 500,
    expectedRangeText: "~80-200",
    panelMemberships: ["Thyroid Panel"],
  }),

  createNumericLab({
  key: "estradiol",
  group: "Hormones",
  displayName: "Estradiol",
  aliases: [
    "estradiol",
    "estradiol serum level",
    "estradiol serum",
    "e2",
  ],
  unit: "pg/mL",
  plausibilityMin: 1,
  plausibilityMax: 10000,
  expectedRangeText: "lab-dependent",
  panelMemberships: [],
}),

  // =========================
  // Lipids
  // =========================
  createNumericLab({
    key: "total_cholesterol",
    group: "Lipids",
    displayName: "Total Cholesterol",
    aliases: ["cholesterol", "total cholesterol", "chol"],
    unit: "mg/dL",
    plausibilityMin: 20,
    plausibilityMax: 1000,
    expectedRangeText: "~100-240",
    panelMemberships: ["Lipid Panel"],
  }),
  createNumericLab({
    key: "hdl",
    group: "Lipids",
    displayName: "HDL",
    aliases: ["hdl", "hdl cholesterol", "high density lipoprotein"],
    unit: "mg/dL",
    plausibilityMin: 1,
    plausibilityMax: 200,
    expectedRangeText: "~40-100",
    panelMemberships: ["Lipid Panel"],
  }),
  createNumericLab({
    key: "ldl",
    group: "Lipids",
    displayName: "LDL",
    aliases: ["ldl", "ldl cholesterol", "low density lipoprotein", "ldl calculated", "calc ldl", "calculated ldl"],
    unit: "mg/dL",
    plausibilityMin: 1,
    plausibilityMax: 500,
    expectedRangeText: "~0-190",
    panelMemberships: ["Lipid Panel"],
  }),
  createNumericLab({
    key: "triglycerides",
    group: "Lipids",
    displayName: "Triglycerides",
    aliases: ["triglycerides", "trig", "tg"],
    unit: "mg/dL",
    plausibilityMin: 1,
    plausibilityMax: 3000,
    expectedRangeText: "~0-200",
    panelMemberships: ["Lipid Panel"],
  }),
  createNumericLab({
    key: "non_hdl",
    group: "Lipids",
    displayName: "Non-HDL Cholesterol",
    aliases: ["non-hdl", "non hdl", "non hdl cholesterol", "non-hdl chol", "non hdl chol"],
    unit: "mg/dL",
    plausibilityMin: 1,
    plausibilityMax: 500,
    expectedRangeText: "~0-220",
    panelMemberships: ["Lipid Panel"],
  }),
  createNumericLab({
    key: "chol_hdl_ratio",
    group: "Lipids",
    displayName: "Chol/HDL Ratio",
    aliases: ["chol/hdl ratio", "cholesterol hdl ratio", "cardiac risk ratio"],
    unit: "",
    plausibilityMin: 0.1,
    plausibilityMax: 50,
    expectedRangeText: "~0-6",
    panelMemberships: ["Lipid Panel"],
  }),

  // =========================
  // Iron Studies
  // =========================
  createNumericLab({
    key: "iron",
    group: "Iron Studies",
    displayName: "Iron",
    aliases: ["iron", "serum iron", "fe"],
    unit: "ug/dL",
    plausibilityMin: 1,
    plausibilityMax: 500,
    expectedRangeText: "~40-180",
    panelMemberships: ["Iron Studies"],
  }),
  createNumericLab({
    key: "tibc",
    group: "Iron Studies",
    displayName: "TIBC",
    aliases: ["tibc", "total iron binding capacity", "total iron-binding capacity"],
    unit: "ug/dL",
    plausibilityMin: 50,
    plausibilityMax: 1000,
    expectedRangeText: "~250-450",
    panelMemberships: ["Iron Studies"],
  }),
  createNumericLab({
    key: "uibc",
    group: "Iron Studies",
    displayName: "UIBC",
    aliases: ["uibc", "unsaturated iron binding capacity"],
    unit: "ug/dL",
    plausibilityMin: 0,
    plausibilityMax: 1000,
    expectedRangeText: "~150-375",
    panelMemberships: ["Iron Studies"],
  }),
  createNumericLab({
    key: "iron_saturation",
    group: "Iron Studies",
    displayName: "Iron Saturation",
    aliases: ["iron saturation", "transferrin saturation", "sat", "% saturation", "saturation"],
    unit: "%",
    plausibilityMin: 0,
    plausibilityMax: 100,
    expectedRangeText: "~15-50",
    panelMemberships: ["Iron Studies"],
  }),
  createNumericLab({
    key: "ferritin",
    group: "Iron Studies",
    displayName: "Ferritin",
    aliases: ["ferritin"],
    unit: "ng/mL",
    plausibilityMin: 1,
    plausibilityMax: 10000,
    expectedRangeText: "~10-300",
    panelMemberships: ["Iron Studies"],
  }),
  createNumericLab({
    key: "transferrin",
    group: "Iron Studies",
    displayName: "Transferrin",
    aliases: ["transferrin"],
    unit: "mg/dL",
    plausibilityMin: 1,
    plausibilityMax: 1000,
    expectedRangeText: "~200-360",
    panelMemberships: ["Iron Studies"],
  }),

  // =========================
  // Vitamins
  // =========================
  createNumericLab({
    key: "vitamin_d_25oh",
    group: "Vitamins",
    displayName: "Vitamin D 25-OH",
    aliases: [
      "vitamin d",
      "vitamin d 25",
      "vitamin d 25-oh",
      "25 oh vitamin d",
      "25-hydroxy vitamin d",
      "vit d",
    ],
    unit: "ng/mL",
    plausibilityMin: 1,
    plausibilityMax: 300,
    expectedRangeText: "~20-100",
    panelMemberships: [],
  }),
  createNumericLab({
    key: "vitamin_b12",
    group: "Vitamins",
    displayName: "Vitamin B12",
    aliases: ["vitamin b12", "b12", "cobalamin"],
    unit: "pg/mL",
    plausibilityMin: 1,
    plausibilityMax: 5000,
    expectedRangeText: "~200-1200",
    panelMemberships: [],
  }),
  createNumericLab({
    key: "folate",
    group: "Vitamins",
    displayName: "Folate",
    aliases: ["folate", "folic acid", "serum folate"],
    unit: "ng/mL",
    plausibilityMin: 0,
    plausibilityMax: 100,
    expectedRangeText: "~3-20",
    panelMemberships: [],
  }),

  // =========================
  // Infectious Disease / STD
  // =========================
  createCategoricalLab({
    key: "hiv_1_2_ab_ag",
    group: "Infectious Disease / STD",
    displayName: "HIV 1/2 Ab/Ag",
    aliases: [
  "hiv",
  "hiv 1/2",
  "hiv ag/ab",
  "hiv ab/ag",
  "hiv screen",
  "hiv 1 2 ab ag",
  "hiv combo",
  "hiv 4th generation",
  "hiv 1/2 antigen antibody",
  "hiv screen hiv screen",
],
    allowedValues: CATEGORICAL_VALUE_SETS.extended,
    panelMemberships: ["STD Panel", "Infectious Disease"],
  }),
  createCategoricalLab({
    key: "syphilis_screen",
    group: "Infectious Disease / STD",
    displayName: "Syphilis Screen",
    aliases: [
      "rpr",
      "syphilis",
      "syphilis screen",
      "syphilis total antibody",
      "treponema pallidum",
      "t pallidum",
      "tp ab",
      "syphilis ab",
    ],
    allowedValues: CATEGORICAL_VALUE_SETS.extended,
    panelMemberships: ["STD Panel", "Infectious Disease"],
  }),
  createCategoricalLab({
    key: "chlamydia",
    group: "Infectious Disease / STD",
    displayName: "Chlamydia",
    aliases: [
      "chlamydia",
      "chlamydia trachomatis",
      "ct",
      "c trachomatis",
      "chlamydia pcr",
      "chlamydia naat",
    ],
    allowedValues: CATEGORICAL_VALUE_SETS.extended,
    panelMemberships: ["STD Panel"],
  }),
  createCategoricalLab({
    key: "gonorrhea",
    group: "Infectious Disease / STD",
    displayName: "Gonorrhea",
    aliases: [
      "gonorrhea",
      "gonorrhoea",
      "neisseria gonorrhoeae",
      "gc",
      "n gonorrhoeae",
      "gonorrhea pcr",
      "gonorrhea naat",
    ],
    allowedValues: CATEGORICAL_VALUE_SETS.extended,
    panelMemberships: ["STD Panel"],
  }),
  createCategoricalLab({
    key: "trichomonas",
    group: "Infectious Disease / STD",
    displayName: "Trichomonas",
    aliases: [
      "trichomonas",
      "trich",
      "trichomonas vaginalis",
      "trichomonas pcr",
      "trichomonas naat",
    ],
    allowedValues: CATEGORICAL_VALUE_SETS.extended,
    panelMemberships: ["STD Panel"],
  }),

  // =========================
  // Hepatitis / Antibodies
  // =========================
  createCategoricalLab({
    key: "hepatitis_a_antibody",
    group: "Hepatitis / Antibodies",
    displayName: "Hepatitis A Antibody",
    aliases: [
  "hepatitis a antibody",
  "hep a antibody",
  "hav ab",
  "anti-hav",
  "hepatitis a total ab",
  "hepatitis a ab",
  "hepatitis a ab igg",
  "hep a ab",
  "hep a ab igg",
  "hav igg",
  "hepatitis a igg",
],
    allowedValues: CATEGORICAL_VALUE_SETS.extended,
    panelMemberships: ["Hepatitis Panel"],
  }),
  createCategoricalLab({
    key: "hepatitis_a_igm",
    group: "Hepatitis / Antibodies",
    displayName: "Hepatitis A IgM",
    aliases: [
  "hepatitis a igm",
  "hep a igm",
  "hav igm",
  "hepatitis a ab igm",
  "hep a ab igm",
],
    allowedValues: CATEGORICAL_VALUE_SETS.extended,
    panelMemberships: ["Hepatitis Panel"],
  }),
  createCategoricalLab({
    key: "hepatitis_b_surface_antigen",
    group: "Hepatitis / Antibodies",
    displayName: "Hepatitis B Surface Antigen",
    aliases: [
  "hbsag",
  "hep b surface antigen",
  "hepatitis b surface antigen",
  "hbv surface antigen",
  "hepatitis b surface ag",
  "hep b surface ag",
  "surface ag",
],
    allowedValues: CATEGORICAL_VALUE_SETS.extended,
    panelMemberships: ["Hepatitis Panel"],
  }),
  createCategoricalLab({
    key: "hepatitis_b_surface_antibody",
    group: "Hepatitis / Antibodies",
    displayName: "Hepatitis B Surface Antibody",
    aliases: [
  "hbsab",
  "anti-hbs",
  "hep b surface antibody",
  "hepatitis b surface antibody",
  "hepatitis b surface ab",
  "hep b surface ab",
  "surface ab",
],
    allowedValues: CATEGORICAL_VALUE_SETS.extended,
    panelMemberships: ["Hepatitis Panel"],
  }),
  createCategoricalLab({
    key: "hepatitis_b_core_antibody",
    group: "Hepatitis / Antibodies",
    displayName: "Hepatitis B Core Antibody",
    aliases: [
  "hbcab",
  "anti-hbc",
  "hep b core antibody",
  "hepatitis b core antibody",
  "hepatitis b core ab",
  "hep b core ab",
  "hepatitis b core ab igg",
  "hep b core ab igg",
  "hbc igg",
],
    allowedValues: CATEGORICAL_VALUE_SETS.extended,
    panelMemberships: ["Hepatitis Panel"],
  }),
  createCategoricalLab({
    key: "hepatitis_b_core_igm",
    group: "Hepatitis / Antibodies",
    displayName: "Hepatitis B Core IgM",
    aliases: [
  "hepatitis b core igm",
  "hep b core igm",
  "hepatitis b core ab igm",
  "hep b core ab igm",
  "hbc igm",
  "anti-hbc igm",
],
    allowedValues: CATEGORICAL_VALUE_SETS.extended,
    panelMemberships: ["Hepatitis Panel"],
  }),
  createCategoricalLab({
    key: "hepatitis_c_antibody",
    group: "Hepatitis / Antibodies",
    displayName: "Hepatitis C Antibody",
    aliases: ["hcv ab", "hep c antibody", "hepatitis c antibody", "anti-hcv"],
    allowedValues: CATEGORICAL_VALUE_SETS.extended,
    panelMemberships: ["Hepatitis Panel"],
  }),
  createCategoricalLab({
    key: "hepatitis_c_rna",
    group: "Hepatitis / Antibodies",
    displayName: "Hepatitis C RNA",
    aliases: ["hcv rna", "hepatitis c rna", "hep c pcr", "hep c viral load"],
    allowedValues: CATEGORICAL_VALUE_SETS.extended,
    panelMemberships: ["Hepatitis Panel"],
  }),

  // =========================
  // Coagulation
  // =========================
  createNumericLab({
    key: "pt",
    group: "Coagulation",
    displayName: "PT",
    aliases: ["pt", "prothrombin time"],
    unit: "sec",
    plausibilityMin: 5,
    plausibilityMax: 100,
    expectedRangeText: "~10-14",
    panelMemberships: [],
  }),
  createNumericLab({
    key: "inr",
    group: "Coagulation",
    displayName: "INR",
    aliases: ["inr", "international normalized ratio"],
    unit: "",
    plausibilityMin: 0.5,
    plausibilityMax: 20,
    expectedRangeText: "~0.8-1.2",
    panelMemberships: [],
  }),
  createNumericLab({
    key: "ptt",
    group: "Coagulation",
    displayName: "PTT",
    aliases: ["ptt", "aptt", "partial thromboplastin time", "activated partial thromboplastin time"],
    unit: "sec",
    plausibilityMin: 10,
    plausibilityMax: 200,
    expectedRangeText: "~25-40",
    panelMemberships: [],
  }),

  // =========================
  // Urinalysis
  // =========================
  createNumericLab({
    key: "urine_specific_gravity",
    group: "Urinalysis",
    displayName: "Urine Specific Gravity",
    aliases: ["specific gravity", "urine specific gravity", "sg"],
    unit: "",
    plausibilityMin: 1.0,
    plausibilityMax: 1.05,
    expectedRangeText: "~1.005-1.030",
    panelMemberships: ["Urinalysis"],
  }),
  createNumericLab({
    key: "urine_ph",
    group: "Urinalysis",
    displayName: "Urine pH",
    aliases: ["urine ph", "ph urine", "ua ph"],
    unit: "",
    plausibilityMin: 3,
    plausibilityMax: 10,
    expectedRangeText: "~5.0-8.0",
    panelMemberships: ["Urinalysis"],
  }),
  createCategoricalLab({
    key: "urine_glucose",
    group: "Urinalysis",
    displayName: "Urine Glucose",
    aliases: ["urine glucose", "glucose urine", "gluc ua"],
    allowedValues: CATEGORICAL_VALUE_SETS.urineDipstick,
    panelMemberships: ["Urinalysis"],
  }),
  createCategoricalLab({
    key: "urine_protein",
    group: "Urinalysis",
    displayName: "Urine Protein",
    aliases: ["urine protein", "protein urine", "prot ua"],
    allowedValues: CATEGORICAL_VALUE_SETS.urineDipstick,
    panelMemberships: ["Urinalysis"],
  }),
  createCategoricalLab({
    key: "urine_ketones",
    group: "Urinalysis",
    displayName: "Urine Ketones",
    aliases: ["ketones", "urine ketones", "ket ua"],
    allowedValues: CATEGORICAL_VALUE_SETS.urineDipstick,
    panelMemberships: ["Urinalysis"],
  }),
  createCategoricalLab({
    key: "urine_blood",
    group: "Urinalysis",
    displayName: "Urine Blood",
    aliases: ["blood urine", "urine blood", "occult blood urine"],
    allowedValues: CATEGORICAL_VALUE_SETS.urineDipstick,
    panelMemberships: ["Urinalysis"],
  }),
  createCategoricalLab({
    key: "urine_leukocyte_esterase",
    group: "Urinalysis",
    displayName: "Urine Leukocyte Esterase",
    aliases: ["leukocyte esterase", "le", "urine leukocyte esterase"],
    allowedValues: CATEGORICAL_VALUE_SETS.urineDipstick,
    panelMemberships: ["Urinalysis"],
  }),
  createCategoricalLab({
    key: "urine_nitrite",
    group: "Urinalysis",
    displayName: "Urine Nitrite",
    aliases: ["nitrite", "urine nitrite"],
    allowedValues: ["Positive", "Negative"],
    panelMemberships: ["Urinalysis"],
  }),
  createCategoricalLab({
    key: "urine_bilirubin",
    group: "Urinalysis",
    displayName: "Urine Bilirubin",
    aliases: ["bilirubin urine", "urine bilirubin"],
    allowedValues: CATEGORICAL_VALUE_SETS.urineDipstick,
    panelMemberships: ["Urinalysis"],
  }),
  createNumericLab({
    key: "urine_rbc",
    group: "Urinalysis",
    displayName: "Urine RBC",
    aliases: ["urine rbc", "rbc urine", "red cells urine"],
    unit: "/hpf",
    plausibilityMin: 0,
    plausibilityMax: 500,
    expectedRangeText: "~0-3",
    panelMemberships: ["Urinalysis"],
  }),
  createNumericLab({
    key: "urine_wbc",
    group: "Urinalysis",
    displayName: "Urine WBC",
    aliases: ["urine wbc", "wbc urine", "white cells urine"],
    unit: "/hpf",
    plausibilityMin: 0,
    plausibilityMax: 500,
    expectedRangeText: "~0-5",
    panelMemberships: ["Urinalysis"],
  }),

  // =========================
  // Urine Protein / Kidney Screening
  // =========================
  createNumericLab({
    key: "microalbumin",
    group: "Urine Protein / Kidney Screening",
    displayName: "Microalbumin",
    aliases: ["microalbumin", "urine microalbumin", "albumin urine"],
    unit: "",
    plausibilityMin: 0,
    plausibilityMax: 10000,
    expectedRangeText: "lab-dependent",
    panelMemberships: [],
  }),
  createNumericLab({
    key: "urine_creatinine",
    group: "Urine Protein / Kidney Screening",
    displayName: "Urine Creatinine",
    aliases: ["urine creatinine", "creatinine urine"],
    unit: "mg/dL",
    plausibilityMin: 1,
    plausibilityMax: 1000,
    expectedRangeText: "lab-dependent",
    panelMemberships: [],
  }),
  createNumericLab({
    key: "albumin_creatinine_ratio",
    group: "Urine Protein / Kidney Screening",
    displayName: "Albumin/Creatinine Ratio",
    aliases: [
      "acr",
      "albumin creatinine ratio",
      "urine albumin creatinine ratio",
      "microalbumin creatinine ratio",
    ],
    unit: "mg/g",
    plausibilityMin: 0,
    plausibilityMax: 10000,
    expectedRangeText: "~0-30",
    panelMemberships: [],
  }),

  // =========================
  // Custom fallback
  // =========================
  {
    key: "custom",
    group: "Other",
    displayName: "Custom Lab",
    aliases: [],
    resultType: "custom",
    unit: "",
    plausibilityMin: null,
    plausibilityMax: null,
    expectedRangeText: "",
    panelMemberships: [],
  },
];

export const LAB_PANELS = {
  CBC: [
    "wbc",
    "rbc",
    "hemoglobin",
    "hematocrit",
    "mcv",
    "mch",
    "mchc",
    "rdw",
    "platelets",
    "mpv",
  ],
  "CBC with Differential": [
    "wbc",
    "rbc",
    "hemoglobin",
    "hematocrit",
    "mcv",
    "mch",
    "mchc",
    "rdw",
    "platelets",
    "mpv",
    "neutrophils_percent",
    "lymphocytes_percent",
    "monocytes_percent",
    "eosinophils_percent",
    "basophils_percent",
    "immature_granulocytes_percent",
    "anc",
    "absolute_lymphocytes",
    "absolute_monocytes",
    "absolute_eosinophils",
    "absolute_basophils",
  ],
  BMP: [
    "sodium",
    "potassium",
    "chloride",
    "co2",
    "bun",
    "creatinine",
    "glucose",
    "calcium",
  ],
  CMP: [
    "sodium",
    "potassium",
    "chloride",
    "co2",
    "bun",
    "creatinine",
    "glucose",
    "calcium",
    "total_protein",
    "albumin",
    "globulin",
    "total_bilirubin",
    "ast",
    "alt",
    "alkaline_phosphatase",
  ],
  "Renal Function Panel": [
    "sodium",
    "potassium",
    "chloride",
    "co2",
    "bun",
    "creatinine",
    "glucose",
    "calcium",
    "phosphorus",
    "albumin",
  ],
  "Lipid Panel": [
    "total_cholesterol",
    "hdl",
    "ldl",
    "triglycerides",
    "non_hdl",
    "chol_hdl_ratio",
  ],
  "Iron Studies": [
    "iron",
    "tibc",
    "uibc",
    "iron_saturation",
    "ferritin",
    "transferrin",
  ],
  "Thyroid Panel": ["tsh", "free_t4", "total_t4", "free_t3", "total_t3"],
  "Hepatitis Panel": [
    "hepatitis_a_antibody",
    "hepatitis_a_igm",
    "hepatitis_b_surface_antigen",
    "hepatitis_b_surface_antibody",
    "hepatitis_b_core_antibody",
    "hepatitis_b_core_igm",
    "hepatitis_c_antibody",
    "hepatitis_c_rna",
  ],
  "STD Panel": [
    "hiv_1_2_ab_ag",
    "syphilis_screen",
    "chlamydia",
    "gonorrhea",
    "trichomonas",
  ],
  Urinalysis: [
    "urine_specific_gravity",
    "urine_ph",
    "urine_glucose",
    "urine_protein",
    "urine_ketones",
    "urine_blood",
    "urine_leukocyte_esterase",
    "urine_nitrite",
    "urine_bilirubin",
    "urine_rbc",
    "urine_wbc",
  ],
};

export const LAB_CATALOG_BY_KEY = LAB_CATALOG.reduce((acc, lab) => {
  acc[lab.key] = lab;
  return acc;
}, {});

export const LAB_ALIAS_INDEX = LAB_CATALOG.reduce((acc, lab) => {
  const values = [lab.displayName, ...(lab.aliases || [])];

  values.forEach((alias) => {
    const normalized = normalizeAlias(alias);
    if (!normalized) return;
    acc[normalized] = lab.key;
  });

  return acc;
}, {});

export function findLabByKey(key) {
  return LAB_CATALOG_BY_KEY[key] || null;
}

export function findLabByAlias(alias) {
  const normalized = normalizeAlias(alias);
  if (!normalized) return null;

  const key = LAB_ALIAS_INDEX[normalized];
  if (!key) return null;

  return LAB_CATALOG_BY_KEY[key] || null;
}

export function getPanelLabDefinitions(panelName) {
  const keys = LAB_PANELS[panelName] || [];
  return keys
    .map((key) => LAB_CATALOG_BY_KEY[key])
    .filter(Boolean);
}

export function getGroupedLabCatalog() {
  return LAB_CATALOG.reduce((acc, lab) => {
    if (!acc[lab.group]) acc[lab.group] = [];
    acc[lab.group].push(lab);
    return acc;
  }, {});
}

export function isNumericLab(lab) {
  return lab?.resultType === "numeric";
}

export function isCategoricalLab(lab) {
  return lab?.resultType === "categorical";
}

export function valueLooksSuspicious(lab, value) {
  if (!lab || lab.resultType !== "numeric") return false;
  if (value === null || value === undefined || value === "") return false;

  const numeric = Number(String(value).replace(/,/g, "").trim());
  if (Number.isNaN(numeric)) return false;

  if (lab.plausibilityMin !== null && numeric < lab.plausibilityMin) return true;
  if (lab.plausibilityMax !== null && numeric > lab.plausibilityMax) return true;

  return false;
}