export const INITIAL_PATIENTS = [
  {
    id: 1,
    mrn: "100234",
    firstName: "Maria",
    lastName: "Gonzalez",
    preferredName: "Mari",
    last4ssn: "2222",
    dob: "1992-06-18",
    age: "33",
    phone: "(555) 222-1111",
    sex: "Female",
    ethnicity: "Hispanic or Latino",
    pronouns: "She/Her",
    ttuStudent: false,
    allergies: "NKDA",
    medications: [
      {
        id: 1,
        name: "Ibuprofen",
        dosage: "200 mg",
        frequency: "PRN",
        route: "Oral",
        isActive: true,
      },
    ],
    encounters: [
      {
        id: 1001,
        clinicDate: "3/1/2026",
        createdAt: new Date().toISOString(),
        newReturning: "Returning",
        visitLocation: "In Clinic",
        chiefComplaint: "Headache",
        notes: "",
        transportation: "Bus/Public Transport",
        needsElevator: false,
        spanishSpeaking: true,
        mammogramPapSmear: "N/A",
        fluShot: "UTD",
        htn: false,
        dm: false,
        labsLast6Months: "",
        tobaccoScreening: "",
        dermatology: "N/A",
        ophthalmology: "N/A",
        optometry: "N/A",
        diabeticEyeExamPastYear: "N/A",
        physicalTherapy: "N/A",
        mentalHealthCombined: "N/A",
        counseling: "N/A",
        anyMentalHealthPositive: false,
        status: "Waiting",
        assignedStudent: "",
        assignedUpperLevel: "",
        roomNumber: "",
        vitalsHistory: [],
        soapSubjective: "",
        soapObjective: "",
        soapAssessment: "",
        soapPlan: "",
        soapSavedAt: "",
      },
    ],
  },
];